# UNITA' 5 CLUSTERING

In [1]:
import numpy as np
import pandas as pd

In [6]:
v1 = np.array([2, 8])
v2 = np.array([6, 7])

delta = v2 - v1

dist = np.sqrt(delta[0] ** 2 + delta[1] ** 2)
dist

np.float64(4.123105625617661)

In [ ]:
c1 = np.array([5, 8, 2]) # A(5, 8, 2)
c2 = np.array([6, 4, 3]) # A(6, 4, 3)

delta x1 = 6 - 5
delta x2 = 4 - 8
delta x3 = 3 - 2

In [5]:
cx = c2 - c1
cx

array([ 1, -4,  1])

In [7]:
np.sqrt(cx[0] ** 2 + cx[1] ** 2 + cx[2] ** 2)

np.float64(4.242640687119285)

come creo un vettore di numeri casuali di N dimensioni

In [11]:
a1 = np.random.randint(low = 1, high = 15, size = 10)
a2 = np.random.randint(low = 1, high = 15, size = 10)
print(a1, a2)

[14  9  8  1  9  5 13  3  2 12] [ 6  1 11 14  8  9  8  8  3  2]


In [12]:
ax = a2 - a1

In [15]:
ax_2 = ax ** 2
print(ax_2)


[ 64  64   9 169   1  16  25  25   1 100]


In [16]:
summax_2 = np.sum(ax_2)

In [18]:
distax = np.sqrt(summax_2)
print(distax)

21.77154105707724
